### PR TITLE
Adding Docker and .NET Core 2.1 support

### PR DESCRIPTION
**Pull request by kdcllc**
Issues# 61.

This is a starting point for Docker and .NET Core 2.1.2 transition.

### CODE REVIEW

**Comment by JudahGabriel** [comment]
Max, I'm new to Docker. Does using Docker dictate that we must use Docker in production? Or is this just for local environments?

**Comment by kdcllc** [comment]
We do not need to have containers inside of Azure for now, the deployment still can continue as Web App for Azure. I believe you are using Publish to accomplish that. So keep it the same way. If you don't want to use Docker locally simply set up Chavah project as start up.

**Comment by kdcllc** [comment]
Sometimes you need to restart Docker and it refreshes the issue with this message.

**Comment by JudahGabriel** [comment]
Max, are you able to startup the Chavah.NetCore project locally? After merging this request, I can't start the project; it exits immediately. Are you seeing this?

**Pull request merged**
