### PR TITLE
Initial Bundling and Minification

### PR DESCRIPTION
**Pull request by kdcllc**
@JudahGabriel,

So, in a nutshell Microsoft introduced bundleconfig.json with BuildBundlerMinifier nuget package that directly integrates with dotnet CLI. So to bundle from command line run:
```
dotnet bundle
```
Otherwise the bundles are build upon regular build of the project.

In addition to specify different environments we use:
```
<environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</environment>
<environment names="Staging,Production">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</environment>
```
I hope to work on it more.

### CODE REVIEW

**Comment by JudahGabriel** [comment]
You are awesome! And thanks for the explainer on how the new bundling works. That sounds good. Have a great shabbat.

**Comment by kdcllc** [comment]
I know the One Who is Awesome, me not so much. It is my privilege to help you in anyway I can.
Shabbat Shalom to you and your family as well!

**Comment by kdcllc** [comment]
@JudahGabriel, I just came across ASP.NET Core 2.0 library that mimics the Optimization in previous versions to a degree https://github.com/ligershark/WebOptimizer.

**Comment by JudahGabriel** [comment]
Oh, interesting. What do you suggest? 

I'm opened to either. I'm currently playing with bundling in an ASP.NET Core app at my day job...was going to try out the waters and see how it goes.

**Comment by kdcllc** [comment]
I am still trying to evaluate the both solution. I might be worth our effort considering migrating to RazorPages when needed https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?tabs=visual-studio and WebApi for the other. I might have sometime this week to continue the migration thru the bundling. I wanted to run by you so we are on the same page.

**Comment by JudahGabriel** [comment]
Alright, let me know what you find after evaluation. Later today or tomorrow, I should have a better grasp on using bundleconfig.json in an ASP.Net Core project; I'll let you know my thoughts.

Razor Pages: related to bundling or tangential? I'm all for trying out new tech where it makes sense. My current focus is getting Chavah.Core running and deployed.

**Comment by kdcllc** [comment]
Razor Pages came up with WebOptimizer and it make sense down the road to use because it might make it cleaner for the code readability. I agree with the goal of making it work first!

**Pull request merged**
