### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kdcllc**
This is initial pull request for the work ahead of us.

### CODE REVIEW

**Comment by kdcllc** [comment]
Initial pull request

**Comment by JudahGabriel** [comment]
So, I've left out the web config deliberately because it contains app secrets, such as email credentials, database connection strings, etc.

I'm willing to merge this in, but it will mean we need to move app secrets to some other location. This article lays out how to do that: https://www.asp.net/identity/overview/features-api/best-practices-for-deploying-passwords-and-other-sensitive-data-to-aspnet-and-azure and I can make that happen.

**Comment by JudahGabriel** [comment]
I've merged your PR. I've just now committed a few related items:

- The real web.config, web.debug.config, and web.release.config
- Moved the secrets out of web config and into AppSettings.Debug.Secrets.config and AppSettings.Release.Secrets.config
- Moved the connection strings out of web config and into ConnectionStrings.Debug.Secrets.config and ConnectionStrings.Release.Secrets.config

I've also updated .gitignore to exclude these secrets files. If you need the debug secrets, just shoot me an email and I'll send them over.

**Comment by kdcllc** [comment]
That is great, I had these changes as well in my next pull request. I will need to get your latest first. My goal right now to be able to run the code completely locally:
1. Sample music files with album art
2. Seed database with sample data
3. Simple unit tests for C#

Thanks, Max

**Comment by kdcllc** [comment]
I want to set up seeder with simple data points, so if we have other devs who would like to assist they can without special info. For emails, I was thinking using configuration to write to txt files. What are your thoughts on that?

**Comment by JudahGabriel** [comment]
Sure, I'm cool with setting up a seed function to get started easier, if that's what you mean.

> "For emails, I was thinking using configuration to write to txt files. What are your thoughts on that?"

You're talking about any time we send emails in the app, to replace that to write to txt files in debug, and making that happen via config? If that's what you mean, sure. I'm OK with sending emails even in debug, but if you want to move that out so it writes to txt files instead in debug, sure, it would be a nice-to-have.

**Pull request merged**
